### ISSUE TITLE
How to parse xml that has "xmlns" instead of "xmls:ans1"

### ISSUE THREAD

**Issue by markus1189** [TinkoffCreditSystems/phobos#68]
Hey :wave: :smile: ,

I am trying to read the following xml:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<foo xmlns="foo.com">
    <isFoo>true</isFoo>
</foo>
```

With the following code:

```scala
import scala.io.Source

import ru.tinkoff.phobos.annotations.{XmlCodec, XmlnsDef}
import ru.tinkoff.phobos.configured.ElementCodecConfig
import ru.tinkoff.phobos.decoding._

@XmlnsDef("foo.com")
case object foo

object FooDefinitions {

  val config: ElementCodecConfig = ElementCodecConfig.default.withNamespaceDefined(foo)
}

@XmlCodec("foo", FooDefinitions.config)
case class Foo(isFoo: Boolean)

object FooMain extends App {

  val input = Source.fromResource("foo.xml").getLines().mkString("\n")

  val decoded = XmlDecoder[Foo].decode(input)
  println(decoded)
}
```

However if I run `FooMain` I get:

```
Left(ru.tinkoff.phobos.decoding.DecodingError: Error while decoding XML: Invalid namespace. Expected no namespace, but found 'foo.com'
	In element 'foo'
     )
```

It works if I change the xml to have `xmls:ans1` instead of `xmls`, however I don't have control over the received XML.

## Question
How can I use `phobos` to parse the above XML?

**Comment by valentiay** [comment]
Hi! 
You should specify namespace in `XmlDecoder` and for `isFoo` parameter, because `xmlns="foo.com"` defines namespaces for both `<foo>` and `<isFoo>` elements.

There are two options:
* you can either define default namespace in config:
  ```scala
  object FooDefinitions {
    val config: ElementCodecConfig =
      ElementCodecConfig.default.withNamespaceDefined(foo).withElementsDefaultNamespace(foo)
  }

  @XmlCodecNs("foo", foo, FooDefinitions.config)
  case class Foo(isFoo: Boolean)
   ```
* or you can specify namespaces for case class parameters with annotation (if you have several parameters, you have to specify annotation for each one):
  ```scala
  object FooDefinitions {
    val config: ElementCodecConfig =
      ElementCodecConfig.default.withNamespaceDefined(foo)
  }

  @XmlCodecNs("foo", foo, FooDefinitions.config)
  case class Foo(@xmlns(foo) isFoo: Boolean)
  ```

In both cases you have to change `@XmlCodec("foo", FooDefinitions.config)` to `@XmlCodecNs("foo", foo, FooDefinitions.config)`.

Here is full code for both options: [option1](https://scastie.scala-lang.org/3W0GXkSwS76dEsDiKtPPYg), [option2](https://scastie.scala-lang.org/M2t8g9naTFqeilUlReLXqA)

I think, I should add docs for config options, because their implementation isn't obvious

**Comment by markus1189** [comment]
Thanks that works :heart:
